-- Setting important key binding
require('custom-commands')
-- installing plugins
require('plugins')
require('colorscheme')
require('mason-config')
require('gopls')
require('code-completion')
require('file-explorer')
require('custom-keys')
require('debugging')
require('syntax-highlight')
require('file-finder')
require('status')
require('lsp-saga')
require('tree-sitter')
require('gitsign-config')
