-- Setting important key binding
require("custom-commands")
-- installing plugins
require("plugins")
require("colorscheme")
-- commenting first thing to do
require("comment")
require("comment")
require("mason-config")
require("go-config")
require("code-completion")
require("file-explorer")
require("custom-keys")
require("debugging")
require("syntax-highlight")
require("file-finder")
require("status")
require("lsp-saga")
require("tree-sitter")
require("gitsign-config")
require("lua-config")
require("cpp-config")
require("python-config")
require("linter")
require("json-config")
require("yaml-config")
require("formatter")
require("rename")
require("ast-grep-config")
